baseURL = "https://www.maximeferon.fr/"
languageCode = "en-us"
title = "Maxime Feron"

theme = "aerial"

[params]
  name = "Maxime Feron"
  about = "DevOps &nbsp;&bull;&nbsp; OVH"
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  #bg_scroll = "no-scroll"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/maxferon"
  target = "_blank"

[[params.social]]
  medium = "Linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/maximeferon/"
  target = "_blank"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/mferon"
  target = "_blank"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/maxime.feron"
  target = "_blank"
